export default {
  chain: 'chain',
  crankArm: 'crank-arm',
  derailleur: 'derailleur',
  fork: 'fork',
  frame: 'frame',
  frontGear: 'front-gear',
  grip: 'grip',
  handlebar: 'handlebar',
  hub: 'hub',
  part: 'part',
  pedal: 'pedal',
  rearGear: 'rear-gear',
  rim: 'rim',
  saddle: 'saddle',
  seatpost: 'seatpost',
  stem: 'stem',
  tire: 'tire',
  wheel: 'wheel',
};
